sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root

  cos:
    endpoint: ap-beijing  # 例如：北京区域的 endpoint，具体区域请替换
    access-key-id: xxxxx # 你的腾讯云 Access Key ID
    access-key-secret: xxxx # 你的腾讯云 Access Key Secret
    bucket-name: xxxxx  # 你的 COS 存储桶名称


---
sky:
  redis:
    host: 192.168.0.108
    port: 6379
    database: 0
    password: 123456

---
sky:
  wechat:
    appid: xxxxxx
    secret: xxxxxx